name: Publish

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    paths:
      - "src/manifest.json"

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build
        run: |
          npm ci
          zip -r ./dist/publish.zip ./src
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
          file-path: dist/publish.zip
          extension-id: fpdogcffloghmjkkgnaknfiflajkhccp
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
